name: Publish to PyPI

on:
  push:

  release:
    types: [published]

jobs:
  build:
    name: Build Package
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Fetch all history for all tags and branches
        run: git fetch --prune --unshallow

      - name: Set up Python
        uses: actions/setup-python@v3.1.1
        with:
          python-version: 3.7

      - name: Install dependencies
        run: |
          pip install wheel
          pip install --upgrade pip
          pip install --upgrade poetry coveralls poetry-dynamic-versioning
          poetry install

      - name: Mypy
        run: |
          poetry run mypy --pretty -p teleme

      - name: Lint with flake8
        run: |
          poetry run flake8 .

      - name: Build Packages
        run: poetry build

      - name: Upload Artifacts
        uses: actions/upload-artifact@v2
        with:
          name: dist
          path: dist/

  publish-pypi:
    name: Publish to PyPI
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Download Artifacts
        uses: actions/download-artifact@v2

      - name: Publish package
        if: github.event_name == 'release'
        uses: pypa/gh-action-pypi-publish@v1.5.0
        with:
          user: __token__
          password: ${{ secrets.pypi_token }}

      - name: Publish package to TestPyPI
        if: github.event_name == 'push'
        uses: pypa/gh-action-pypi-publish@v1.5.0
        with:
          user: __token__
          password: ${{ secrets.test_pypi_token }}
          repository_url: https://test.pypi.org/legacy/
