name: Publish to PyPI

on:
  push:

  release:
    types: [published]

jobs:
  build:
    name: Build Package
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.7

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip setuptools
          pip install flake8 mypy wheel
          pip install -r requirements.txt

      - name: Lint with flake8
        run: flake8 . --ignore=W605  # ignore versioneer

      - name: Rename Versioneer
        run: mv teleme/_version.py teleme/_version.py.bak

      - name: Mypy
        run: mypy --python-version 3.7 --strict --show-traceback --ignore-missing-imports --show-error-context --implicit-reexport --pretty -p teleme

      - name: Rename Versioneer
        run: mv teleme/_version.py.bak teleme/_version.py

      - name: Build Packages
        run: python setup.py build sdist bdist_wheel

      - name: Upload Artifacts
        uses: actions/upload-artifact@v2
        with:
          name: dist
          path: dist/

  publish-pypi:
    name: Publish to PyPI
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Download Artifacts
        uses: actions/download-artifact@v2

      - name: Publish package
        if: github.event_name != 'push'
        uses: pypa/gh-action-pypi-publish@v1.1.0
        with:
          user: __token__
          password: ${{ secrets.pypi_token }}

      - name: Publish package to TestPyPI
        uses: pypa/gh-action-pypi-publish@v1.1.0
        with:
          user: __token__
          password: ${{ secrets.test_pypi_token }}
          repository_url: https://test.pypi.org/legacy/

